# fly.toml app configuration file generated for lnksy on 2026-03-04T13:45:45+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lnksy'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[[mounts]]
  source = 'url_short_data'
  destination = '/app/db'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
